version: '2'

services:
  app:
    image: '08-flask-snippets'
    build:
      context: .
    ports:
      - "5000:5000"
    container_name: 08-flask-snippets
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/db1
      - POSTGRES_USER=linux_user
      - POSTGRES_PASSWORD=linux_user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    restart: unless-stopped

